### ISSUE TITLE
Typo in parameter key.

### ISSUE THREAD

**Issue by abilash44** [aws-samples/amazon-connect-with-amazon-lex-genai-capabilities#2]
Typo:
![image](https://github.com/aws-samples/amazon-connect-with-amazon-lex-genai-capabilities/assets/7634986/0eb0da46-6c4b-4b77-b8de-37176ff82aab)

PredictionConfidence is the correct keyname.

Also a follow up question - Does this stack create a new Amazon Connect instance? What if I want to use an existing instance?

**Comment by alasross** [comment]
Thank you @abilash44.

The deployment script will deploy a new Amazon Connect instance for the demo. The Lambda that gets deployed works with any Amazon Lex bot that you create, then you can associate that Lex bot into your existing Amazon Connect instance. Currently today, the deployment doesn't take into consideration existing instances and would have to be done manually.
