### ISSUE TITLE
How to get languages to work

### ISSUE THREAD

**Issue by abilash44** [aws-samples/amazon-connect-with-amazon-lex-genai-capabilities#3]
Hi
I put in some german words and the bot kept failing.

![image](https://github.com/aws-samples/amazon-connect-with-amazon-lex-genai-capabilities/assets/7634986/190cbf16-15b0-40dd-9147-83f78706c72e)

What needs to be done to get language to work?  Do I need to create a new language in the lex bot or will it work within English ?

**Comment by alasross** [comment]
Hi @abilash44, can you kindly re-clone the repo and try it again one more time? We identified some issues and pushed a fix. The language should work out of the box without further configuration. Just note that for voice channels (e.g., using Amazon Connect), you would have to create a new locale in the the bot for the ASR to pick up the right language. Otherwise, for chat, it'll work out of the box.

**Comment by abilash44** [comment]
Thank you for fixing it so soon. This is really great feature. If I understand it correctly all I have to do is to add Spanish Lanuage and it will work?

eg language from LEX 

![image](https://github.com/aws-samples/amazon-connect-with-amazon-lex-genai-capabilities/assets/7634986/39c71e1e-b41e-48fa-a6ed-40c3be31e7d8)


Does it require any settings in Amazon Connect side or if the user speaks english or a mix of english and spanish the bedrock will work? ( still have to test out the new changes ) Just asking to understand how it is built.

**Comment by alasross** [comment]
When you add in a new language, you will need to specify the lambda and version/alias under Deployment > Aliases > Languages > Click on the Language > specify the Lambda and alias.  

Then, you'll need to enable "Run a lambda function to fulfill the intent and inform users of the status when it's complete" under the FallbackIntent. 

Here's a reference https://docs.aws.amazon.com/lexv2/latest/dg/lambda-attach.html


On the Amazon Connect side, when you configure 'Get customer input' block, you specify the Amazon Lex Bot that you've attached the Lambda to. Then pass in the available intents as shown on the blog under the "Filter available intents based on contact flow attributes" https://aws.amazon.com/blogs/machine-learning/enhance-amazon-connect-and-lex-with-generative-ai-capabilities/

For you to use Amazon Lex's different locales, you do need to set the language as part of the Amazon Connect contact flow that matches the locale configured in Amazon Lex.
