### ISSUE TITLE
Why is lambda a container image?

### ISSUE THREAD

**Issue by abilash44** [aws-samples/amazon-connect-with-amazon-lex-genai-capabilities#5]
Hi
This post is more of why it is built this way question. 

My experience is with AWS Lambda, so container image is new to me. Any specific reason container image is used for lambda?

Can I simply use the lambda code in a regular lambda and will it work?

I am not even a novice with container and do not know how to edit the lambda code if I want to customize or play around with it. How would I do dev work on container images and test them running test cases?

**Comment by alasross** [comment]
The code uses Langchain as one of the dependencies and the sizes exceeds Lambda layer limits. You can refer to the Dockerfile, change the lambda_function.py, build and push to ECR.
